#!/usr/bin/env node

/**
 * Environment Setup Script
 *
 * This script helps set up the .env file for the Expo app.
 * It detects your local IP address and creates a .env file with the API URL.
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ENV_FILE_PATH = path.resolve(__dirname, "../.env");
const ENV_EXAMPLE_PATH = path.resolve(__dirname, "../.env.example");

/**
 * Gets the local IP address of the machine
 * @returns {string|null} The local IP address or null if not found
 */
function getLocalIP() {
  try {
    const os = require("os");
    const interfaces = os.networkInterfaces();

    // Look for the first non-internal IPv4 address
    for (const name of Object.keys(interfaces)) {
      for (const iface of interfaces[name]) {
        // Skip internal (loopback) and non-IPv4 addresses
        if (iface.family === "IPv4" && !iface.internal) {
          return iface.address;
        }
      }
    }
  } catch (error) {
    console.error("Error getting local IP:", error);
  }
  return null;
}

/**
 * Gets the API port from environment or defaults to 8080
 * @returns {number} The API port
 */
function getAPIPort() {
  return process.env.API_PORT || 8080;
}

/**
 * Main setup function
 */
function setupEnv() {
  console.log("🔧 Setting up environment variables for Expo app...\n");

  // Check if .env already exists
  if (fs.existsSync(ENV_FILE_PATH)) {
    console.log("⚠️  .env file already exists.");
    const readline = require("readline");
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    rl.question("Do you want to overwrite it? (y/N): ", (answer) => {
      if (answer.toLowerCase() !== "y" && answer.toLowerCase() !== "yes") {
        console.log("Skipping .env file creation.");
        rl.close();
        return;
      }
      createEnvFile();
      rl.close();
    });
  } else {
    createEnvFile();
  }
}

/**
 * Creates the .env file with detected IP address or provided URL
 */
function createEnvFile() {
  const readline = require("readline");
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log("\n📋 Setup Options:");
  console.log("1. Development (use local IP for local development)");
  console.log("2. Production (use App Runner or deployed URL)");
  console.log("3. Custom (enter your own URL)");

  rl.question("\nSelect option (1/2/3): ", (option) => {
    let apiUrl;

    if (option === "1") {
      // Development mode - use local IP
      const localIP = getLocalIP();
      const apiPort = getAPIPort();

      if (!localIP) {
        console.error(
          "❌ Could not detect local IP address. Please set EXPO_PUBLIC_API_URL manually."
        );
        console.log("\nTo set it manually:");
        console.log(`1. Create a file: ${ENV_FILE_PATH}`);
        console.log(
          `2. Add: EXPO_PUBLIC_API_URL=http://YOUR_LOCAL_IP:${apiPort}`
        );
        console.log(
          "\nTo find your IP address:\n  macOS/Linux: ifconfig\n  Windows: ipconfig"
        );
        rl.close();
        return;
      }

      apiUrl = `http://${localIP}:${apiPort}`;
      console.log(`\n✅ Using development URL: ${apiUrl}`);
    } else if (option === "2") {
      // Production mode - App Runner URL
      rl.question(
        "\nEnter your App Runner URL (e.g., https://xxxxx.ap-south-1.awsapprunner.com): ",
        (url) => {
          if (!url || !url.trim()) {
            console.error("❌ URL cannot be empty.");
            rl.close();
            return;
          }
          apiUrl = url.trim();
          writeEnvFile(apiUrl, "production");
          rl.close();
        }
      );
      return;
    } else if (option === "3") {
      // Custom URL
      rl.question(
        "\nEnter your API URL (e.g., http://192.168.1.100:8080 or https://api.example.com): ",
        (url) => {
          if (!url || !url.trim()) {
            console.error("❌ URL cannot be empty.");
            rl.close();
            return;
          }
          apiUrl = url.trim();
          writeEnvFile(apiUrl, "custom");
          rl.close();
        }
      );
      return;
    } else {
      console.error("❌ Invalid option. Please select 1, 2, or 3.");
      rl.close();
      return;
    }

    writeEnvFile(apiUrl, "development");
    rl.close();
  });
}

/**
 * Writes the .env file with the provided API URL
 */
function writeEnvFile(apiUrl, mode) {
  const localIP = getLocalIP();
  const apiPort = getAPIPort();
  const isProduction = apiUrl.startsWith("https://");

  let envContent = `# Expo Environment Variables
# This file was generated by setup-env.js
# 
# IMPORTANT: Environment variables must be prefixed with EXPO_PUBLIC_ to be accessible in the app
# 
`;

  if (mode === "development") {
    envContent += `# Development mode - using local IP address
# Make sure your API server is running on port ${apiPort}
# Local IP detected: ${localIP || "unknown"}
#
`;
  } else if (mode === "production") {
    envContent += `# Production mode - using App Runner/deployed URL
# This is your production API endpoint
#
`;
  } else {
    envContent += `# Custom API URL configuration
#
`;
  }

  envContent += `# To switch between development and production:
# - Development: http://YOUR_LOCAL_IP:${apiPort}
# - Production: https://your-app-runner-url.awsapprunner.com
#
# After changing this file, restart Expo: stop and run 'npm start' again

EXPO_PUBLIC_API_URL=${apiUrl}
`;

  try {
    fs.writeFileSync(ENV_FILE_PATH, envContent);
    console.log("\n✅ Created .env file successfully!");
    console.log(`\n📝 API URL set to: ${apiUrl}`);
    if (mode === "development") {
      console.log(
        "\n⚠️  Important: Make sure your API server is running on this address."
      );
    } else if (mode === "production") {
      console.log("\n✅ Production URL configured. Your app will use the deployed API.");
    }
    console.log(
      "\n💡 To restart Expo with the new environment variables, stop and run 'npm start' again."
    );
  } catch (error) {
    console.error("❌ Error creating .env file:", error.message);
  }
}

// Run the setup
setupEnv();

